### ISSUE TITLE
Searching for successor

### ISSUE THREAD

**Issue by coreGreenberet** [hahn-th/homematicip-rest-api#383]
To make long story short: I will move into a house this year and it will be powered by loxone and not hmip.
Therefore I won't be able to support this library anymore as I'm just missing the equipment.

If you are interested to maintain the library, then please get in contact with me. Either leave a comment or contact me on the discord channel

**Comment by sircuri** [comment]
What do you mean by missing the equipment. I could try to keep this project alive, but I only have an Access Point, Heating Actuator (CH switch), 2 6 channel 230V floor heating modules and 4 thermostats (with LCD and control wheel)

How did you manage to implement all the other devices?
How did you manage to capture the possible REST endpoints?

I'm not sure if I'm the right person as Python is not really my main language. But I could help with providing support.

**Comment by coreGreenberet** [comment]
Well since I'm changing to loxone I will sell all of my hmip stuff.

I've implemented most of the devices thanks to other people which have sent me their access point configurations see #114 
In the beginning I've used an HTTPS proxy between my mobile phone and the internet. That way I could see what happens, when I've changed something.
Since this was only working for devices which I own and not for the devices in the community, I've started to dig into the app code with running the apk through jadx.

**Comment by steckenpferd** [comment]
@SukramJ can you not take over?

**Comment by SukramJ** [comment]
@steckenpferd No, i'll also withdraw. EQ-3 has no real commitment to OSS.

**Comment by dmar29** [comment]
Hi @coreGreenberet, maybe I can support a little here. But I would definitely have to familiarise myself with this task. I have basic knowledge of Python, Home Assistant and HomematicIP running. Can we talk about this? Thanks

**Comment by rhoegen** [comment]
Same here, I probably don't have the time to take over the whole library, but can contribute new devices if I roughly know what to do.

**Comment by coreGreenberet** [comment]
basically adding a new device is based on these steps

* add the value in the enums in [/homematicip/base/enums.py](https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/base/enums.py)
* create the correct classes (Async & legacy/request based)  [/homematicip/device.py](https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/device.py) & [/homematicip/aio/device.py](https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/aio/device.py)
  * optional you might need a new functional_channel: [/homematicip/base/functionalChannels.py](https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/base/functionalChannels.py)
* create the class maps in [/homematicip/class_maps.py](https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/class_maps.py) & [/homematicip/aio/class_maps.py](https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/aio/class_maps.py)
* add a stock entry in [/homematicip_demo/json_data/home.json](https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip_demo/json_data/home.json) and create the corresponding tests

**Comment by user45876** [comment]
Sorry for warming this up and potentially being naive, but has anybody already tried getting EQ3 into the boat here? 
I think it would be in their absolutely best interest to officially support this.

@SukramJ May I ask, if they said something or what happened?

For me, hmip_cli is crucial :-/

**Comment by hahn-th** [comment]
i will have a look for the error, but cannot make any promisses as i am not really into home-assistant development and python.

**Comment by hahn-th** [comment]
@coreGreenberet Thanks for mergin the PR. I tried contacting you using discord regarding succession of the project.
