### ISSUE TITLE
Got cut off from Homematic IP Cloud due to excessive polling by this integration

### ISSUE THREAD

**Issue by Nihilissimis** [hahn-th/homematicip-rest-api#408]
Hello, 

I noticed recently that my Access Point was no longer connected to the HMIP cloud. It turned out that my access was restricted due to an 'excessive amount of polls' from a python script. After killing the plugin and restarting HA. I regained access. 
Please let me know if I can do anything to assist in finding the exact issue.

Thanks for building and maintaining this integration. Very much appreciated.

**Comment by Apollon77** [comment]
What you did? How often you changedx values?

**Comment by Nihilissimis** [comment]
Hello Ingo,

I didn’t do much that I know. 
It seems a process was running wild, trying to poll every 30 seconds according to HMIP second line support. This is apparently too much and you get blocked by their DDoS protection or something. 
Let me know what I can do to replicate the problem. 

Vriendelijke groet / Kind regards,
Niels Mineur

-- Sent from phone

**Comment by sebastianw** [comment]
They changed something. I had this library pull stats every minute for years. Since last week it just gives errors after a while. Error 429 which basically means that you're ratelimited.

**Comment by sebastianw** [comment]
@sebamomann I currently pull data every 10 minutes and that works for now. I'm not happy about that rate so I'm considering switching to a CCU3 control module and ditching the Homematic Cloud completely.

**Comment by imkerkern** [comment]
@sebastianw  I'm considering switching to a CCU3 control module and ditching the Homematic Cloud completely also, but i don't know where i have to start.  I will gladly accept hints.

**Comment by mfrawley** [comment]
@sebastianw how did you configure it to pull data only every so often? Did you write a custom script or fork the project?

**Comment by sebastianw** [comment]
@mfrawley The library itself only pulls data when you call `.get_current_state()` on the `Home()` instance. I increased the time in my tool to call this only every 10 minutes.

**Comment by hahn-th** [comment]
I think its done now.
