### ISSUE TITLE
Since Homematic IP App Update (2.7.4) Alarm Panel doesn't work properly

### ISSUE THREAD

**Issue by Quotenjunkie** [hahn-th/homematicip-rest-api#412]
Hi,

since the Update the Alarm Panel lets me activate the alarm modes (also in the Homematic IP App) but the status doesn't change.
So I am not able to see that the alarm has been set and furthermore I am not able to deactivate it.

Additionally, the HomematicIP INTERNAL SecurityZone and the HomematicIP EXTERNAL SecurityZone are unavailable.

BR

**Comment by steckenpferd** [comment]
https://github.com/coreGreenberet/homematicip-rest-api/issues/383

**Comment by hahn-th** [comment]
Is this still a problem?

**Comment by hahn-th** [comment]
Works for me. I close this issue.
