### ISSUE TITLE
[NEW DEVICE] HMIPW-DRBL4 (Homematic IP Wired Blinds Actuator - 4x channels)

### ISSUE THREAD

**Issue by tomnissing** [hahn-th/homematicip-rest-api#416]
Would be cool if someone could integrate the HMIP-DRBL4 :)
Pls let me know if i can help in any way

Here is my dump file:
[hmip-config_AB16.json.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/6721238/hmip-config_AB16.json.zip)

**Comment by steckenpferd** [comment]
https://github.com/coreGreenberet/homematicip-rest-api/issues/383

**Comment by dominikoyen** [comment]
Yes, this would be beautiful!

**Comment by hahn-th** [comment]
Fixed with Version 1.0.14
