### ISSUE TITLE
Missing HomematicIP Device HmIP-WGC

### ISSUE THREAD

**Issue by K3vb3rt** [hahn-th/homematicip-rest-api#420]
Hello,
I miss the HmIP-WGC in my configuration. There's only the battery state.
JSON is attached.

Looking forward to hear from you :)

Thanks!

[hmip-config_9146.json.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/7114945/hmip-config_9146.json.zip)

**Comment by hahn-th** [comment]
I am search for somebody who can test my changes regarding HmIP-WGC. Please visit Issue #427.
