### ISSUE TITLE
Missing HmIP-WGC

### ISSUE THREAD

**Issue by Marow** [hahn-th/homematicip-rest-api#426]
I am using Home Assistant. I see that HmIP-WGC as Device there, but no functions of it. The functions to open/Close Garage Door is working in HomeMatic IP App but not in Home Assistant

Would be great if you can add that button function to it

Added dump
[hmip-config_2A3A.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/7571328/hmip-config_2A3A.zip)

**Comment by hahn-th** [comment]
I am search for somebody who can test my changes regarding HmIP-WGC. Please visit Issue #427.
