### ISSUE TITLE
Add device HmIP-WGC

### ISSUE THREAD

**Issue by PaKi57** [hahn-th/homematicip-rest-api#427]
Hi,

could you please add device HmIP-WGC to make it possible to open/close a garage door

Please find attached as requested the relevant part of the json file.

Thx a lot!

[hmip-config_HmIP-WGC_json.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/7675348/hmip-config_HmIP-WGC_json.txt)

**Comment by MartinKuhl** [comment]
In the ioBroker Github I found this issue: https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/316
Here someone was able to sniff the API Calls between App an die Cloud services. So this command is needed to control the garage door. Maybe someone find this some kind of useful.

**Comment by MartinKuhl** [comment]
the ioBroker adapter now fully support the HmIP-WGC device. Is someone able to adapt the changes there to this lib?

**Comment by PaKi57** [comment]
Is there anybody so Kind and able to do this for HomeAssistant?

**Comment by hahn-th** [comment]
Do somebody know the rest API url to toggle the door?

**Comment by hahn-th** [comment]
Anybody here who can test my changes?
@MartinKuhl @PaKi57 @Marow @tomnissing

**Comment by PaKi57** [comment]
I would be happy to test it. Could you please give me some advice how to install and test it?

**Comment by PaKi57** [comment]
![image](https://user-images.githubusercontent.com/93467445/179935809-639166d5-7aaf-48c3-869e-e1d05f9e6e14.jpeg)

I van only see this item in my home assistent.

**Comment by hahn-th** [comment]
It is not yet implemented in Home Assistant. Therefore you have to test the library, which HomeAssistant uses for communiation with the Homematic Hub. If this works, i will add the device to HASS
Can you contact me in Discord? 
agonist#6159

**Comment by PaKi57** [comment]
I created a discord account

**Comment by Marow** [comment]
> It is not yet implemented in Home Assistant. Therefore you have to test the library, which HomeAssistant uses for communiation with the Homematic Hub. If this works, i will add the device to HASS Can you contact me in Discord? agonist#6159

i also added you in discord. need tutorial or something but i can test it than also

**Comment by hahn-th** [comment]
Maybe somebody could review the HmIP-WGC pull request https://github.com/home-assistant/core/pull/75733 in HomeAssistant?
It gets not merged until somebody make a review.

**Comment by MartinKuhl** [comment]
Hi @hahn-th I tried to execute the following:
python3 ./hmip_cli.py -d 3014F711A0001318A989F47D --toggle-garage-door --channel 2

3014F711A0001318A989F47D is my WGC Garage Door Contoller here I get the following error:
AttributeError: 'WallMountedGarageDoorController' object has no attribute 'send_impulse_start'

Is there another command I have to use?

**Comment by hahn-th** [comment]
Have you used the latest version?
And are you sure, its channel 2? Just try without the channel arg.

**Comment by MartinKuhl** [comment]
yes, I cloned the repo today and without the channel I get the following error:
Traceback (most recent call last):
  File "./hmip_cli.py", line 853, in <module>
    main()
  File "./hmip_cli.py", line 621, in main
    for c in args.channels:
TypeError: 'NoneType' object is not iterable
