### ISSUE TITLE
Add HmIP-STE2-PCB - Temperature sensor with two resistor elements 

### ISSUE THREAD

**Issue by Maxi2509** [hahn-th/homematicip-rest-api#435]
Hi, 

today i noticed that my temperature sensor with two resistor elements is not yet supported by this integration. i wanted to ask if this could be done in next revision. i added you my Homematic ip config file 

Especially i am asking for HmIP-STE2-PCB
As today i only receive the battery status for this unit.  below i have added you a picture of this device. 

If you need any further information please let me know.

Best regards,
Maxi

[hmip-config_BCF7.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/8079673/hmip-config_BCF7.zip)
![155614_f06_gehmip_ste2_pcb_600x600](https://user-images.githubusercontent.com/77342189/154260200-3d5bef24-99cc-438b-a74f-0471e120c3e4.jpg)

**Comment by kaitomalik** [comment]
Same here, 
WARNING (MainThread) [homematicip.device] There is no class for functionalChannel 'TEMPERATURE_SENSOR_2_EXTERNAL_DELTA_CHANNEL' yet

Thanks, 
Kai

**Comment by Maxi2509** [comment]
Has anybody an idea how to get the two sensors in HA?
i have no idea how to solve this. 

![image](https://user-images.githubusercontent.com/77342189/173335337-e52e9310-a680-4184-bf88-84c53385d4bb.png)

**Comment by hahn-th** [comment]
I have testet it with your config and it works. Sensor is not integrated in HomeAssistant Integration.

**Comment by hahn-th** [comment]
Fixed. Integration in Home-Assistant still has to be implemented
