### ISSUE TITLE
Add HMIP-eTRV-E

### ISSUE THREAD

**Issue by illiumst** [hahn-th/homematicip-rest-api#438]
Hi,

I noticed that my thermostat (HMIP eTRV EVO) is not yet supported by this integration.

Here is my config dump as defined in the wiki:
[hmip-config_0698.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/8229855/hmip-config_0698.txt)

If you need any further information please let me know.

Best regards

**Comment by hahn-th** [comment]
Have you tested it? It should work with current version.
