### ISSUE TITLE
HMIP-STE2-PCB

### ISSUE THREAD

**Issue by MaierA19** [hahn-th/homematicip-rest-api#439]
Hello,

I have the HMIP-STE2_PCB from Homematic IP and I can only see the battery status in Hassio. Can you look at the configuration and try to make the temperature values ​​visible in Hassio?

The Name of the Labels are here:

"label": "",
                    "temperatureExternalDelta": 21.6,
                    "temperatureExternalOne": 3.4,
                    "temperatureExternalTwo": -18.2

Thanks very much
A. Boehmer
[hmip-config_B584 - Kopie.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/8504981/hmip-config_B584.-.Kopie.txt)

**Comment by gtawelt** [comment]
Device is integrated in this Project.
Homeassistant Integration needs Update for this Device
Please open issue at https://github.com/home-assistant/core
