### ISSUE TITLE
HmIP-WLAN-HAP

### ISSUE THREAD

**Issue by Mulberry26** [hahn-th/homematicip-rest-api#442]
The Access Point type I am using is HmIP-WLAN-HAP Has anyone successfully connected to this Access Point through the API?

**Comment by gtawelt** [comment]
I have only the LAN connected HAP. Function should be identical. Did you try to generate an auth token with hmip_generate_auth_token.py ?

**Comment by hahn-th** [comment]
Have you tried accessing it? How was your experience? It could be interessting for everyone.

**Comment by Mulberry26** [comment]
Hello everyone.
I've been busy working on a project lately and only now I have time to post information about it. I would like to say that the answer to the question of whether HmIP-WLAN-HAP can use this API is yes. However, due to its special connection principle, you need to connect it to the WLAN through your cell phone APP Homematic IP first, and then call the api from your computer, which is also in the WLAN, before you can access it.

**Comment by hahn-th** [comment]
Thanks you for your feedback! I gonna mark it as supported!
