### ISSUE TITLE
Add ELV-SH-BS2

### ISSUE THREAD

**Issue by ScooterisT5** [hahn-th/homematicip-rest-api#450]
Please add ELV-SH-BS2 which is "powered by Homematic-IP
I think it is kind of similar to the HMIP-BSL.
It has 2 Channels
The Switch Group is already supported, but not the 2 Channels itself as switches
What can i do to support ?

Cheers
Carsten

**Comment by hahn-th** [comment]
Hi,
are you using Home-Assitant? Please follow these instructions and upload your file here. 
https://www.home-assistant.io/integrations/homematicip_cloud/#what-to-do-if-a-device-is-missing-in-home-assistant

**Comment by ScooterisT5** [comment]
Yes, sure.
Ah, ok - thanks
I`ve stripped the file down a little bit. I hope that's fine.

[hmip-config_F92C.docx](https://github.com/hahn-th/homematicip-rest-api/files/9221357/hmip-config_F92C.docx)

**Comment by hahn-th** [comment]
Can you please add a json or txt file?

**Comment by ScooterisT5** [comment]
is the fine for you ?
[ELV-SH-BS2.txt](https://github.com/hahn-th/homematicip-rest-api/files/9229128/ELV-SH-BS2.txt)

**Comment by hahn-th** [comment]
It would be really great, if you can upload a new dump. If you look in the file, it is full of control caracters and escape signs. I cant use it like that. Just use a simple texteditor, if you really have to manipulate the data before uploading.

**Comment by hahn-th** [comment]
I added the device into the Branch ELV-SH-BS2 (https://github.com/hahn-th/homematicip-rest-api/tree/ELV-SH-BS2)
Can you please get this branch and try to access the switch with the hmip_cli.py file? You need to specifiy the arguments --channel 1 or 2 and and --turn-on or --turn-off. And of course you have to target the device. More info:
`python hmip_cli.y --help`

@ScooterisT5 :)

**Comment by ScooterisT5** [comment]
Hey, 
sorry for my ignorance, but to be honest: i´ve never done this before.
Can you explain how to test, or give a link where i can read a how-to ?

And BTW, i think the HMIP-BS2 is the same. For any reason they named the ready to run retail product HMIP-BS2 and the kit from ELV is the one i have ELV-SH-BS2

**Comment by hahn-th** [comment]
You need python installed. You find it here: https://www.python.org/
Search for a howto on to run python from command line.

Download this zip: https://github.com/hahn-th/homematicip-rest-api/archive/refs/heads/ELV-SH-BS2.zip
Unzip it
Open Commandline and change into the folder
Run: `pip install -r .\requirements.txt` to install requirements

If no errors occured:
Here is described on how to use the commandline-interface (CLI): https://github.com/hahn-th/homematicip-rest-api#usage

**Comment by hahn-th** [comment]
Yes please. And open a new issue please
