### ISSUE TITLE
HmIP-DRDI3 not supported yet.

### ISSUE THREAD

**Issue by gnoffer** [hahn-th/homematicip-rest-api#455]
i would like to have the HmIP-DRDI3 supported. Dump attached.
[hmip-config_F3FC.zip](https://github.com/hahn-th/homematicip-rest-api/files/9469205/hmip-config_F3FC.zip)

**Comment by hahn-th** [comment]
Hi, it is already implemented in this library, but is missing in Homeassistant. You could open an issue there.

**Comment by gnoffer** [comment]
thanks a lot, there is already a[ feature request](https://community.home-assistant.io/t/homematic-hmip-drdi3-support/289981) for long time... shall i open an issue too?

**Comment by gnoffer** [comment]
> Hi, it is already implemented in this library, but is missing in Homeassistant. You could open an issue there.

done @ https://github.com/home-assistant/core/issues/78053
