### ISSUE TITLE
test test_find_and_load_config_file is failing

### ISSUE THREAD

**Issue by MartinKuhl** [hahn-th/homematicip-rest-api#456]
when executing python3 ./test.py

the following test fails:
tests/test_config.py::test_find_and_load_config_file FAILED    

FAILED tests/test_config.py::test_find_and_load_config_file - AssertionError: assert HmipConfig(auth_token=....

**Comment by hahn-th** [comment]
you should call
```
pip install -r requirements_dev.txt
pytest tests
```

**Comment by MartinKuhl** [comment]
I am starting the tests via python3 ./test.py    

I am using a MacOS as operation system, could that be the problem?
So it is not possible to directly call pytest tests.
I am not familiar with the usage of python.

**Comment by hahn-th** [comment]
Hallo, nein das OS sollte keinen Einfluss haben. Kann ich aber nicht ausschließen, da ich kein OSX verwende.
Doch du kannst einzelne Testfälle direkt adressieren. Musst dich mal in die pytest Doku einlesen: https://docs.pytest.org/en/7.1.x/getting-started.html#get-started
Du kannst einzelne Dateien mit angeben `pytest tests/test_devices.py` und dann sogar noch nur bestimmte Testfälle ausführen.
Oder meinst du was anderes?

Ich persönliche rufe die Tests entweder wie oben `pytest tests` auf oder ich habe VisualStudio Code so konfiguriert, dass ich dort einzelne Tests ausführen kann.

Diese test.py und test_aio.py Dateien werden ich wahrscheinlich löschen.

**Comment by MartinKuhl** [comment]
Hi, ich mein, ich kann nicht pytest als Befehl verwenden. Mac sagt, dass es den Befehl nicht kennt, obwohl ich  über pip die dev-requirements installiert hab.

**Comment by hahn-th** [comment]
Das hat spontan google ausgespuckt: https://stackoverflow.com/a/53155231

**Comment by hahn-th** [comment]
Können wir das Issue schließen?

**Comment by MartinKuhl** [comment]
bin heute erst dazu gekommen:  python3 -m pytest
Das Ergebnis war ein Fehler, wieder wie oben: FAILED tests/test_config.py::test_find_and_load_config_file:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/55736453/189430263-fcc0863a-abcb-46fc-b2b9-9fa0adb4a893.png">

**Comment by hahn-th** [comment]
Hast du da noch was weiterverfolgt? Bei mir und auch bei Github läuft der Test problemlos durch. Ich schätze, dass hat vielleicht mit Zugriffsrechten oder ähnlichem zu tun?

**Comment by MartinKuhl** [comment]
Ich schließe das Issue, unter Linux läuft der Test durch, es muss also an der Mac Umgebung liegen.

**Comment by coreGreenberet** [comment]
Ich vermute mal, dass du die deine eigene config global am mac zugänglich gemacht hast. Der test findet sie dann und schlägt dann fehl
