### ISSUE TITLE
Request for Integration of HmIP-DLD (Door lock)

### ISSUE THREAD

**Issue by Maxi2509** [hahn-th/homematicip-rest-api#458]
Hi, 

i would be happy if you could integrate the door lock  HmIP-DLD.
i already read that a lot of users are searching for it. 

![1](https://user-images.githubusercontent.com/77342189/191182745-5d4609d9-14a8-4194-8e55-4a6d182002e7.JPG)

Please find below my config file:

[hmip-config_BCF7.zip](https://github.com/hahn-th/homematicip-rest-api/files/9604647/hmip-config_BCF7.zip)

If you have any questions please ask

Best regards,
Maxi

**Comment by hahn-th** [comment]
Hi, this device is already implemented in this lib and is released in the next version. 
The implementation in HomeAssistant needs more time and i am busy at the moment. 
If someone else have the time to implement it, do it. Just contact me in discord for more informations.

**Comment by hahn-th** [comment]
since 1.0.8 it is supported by this lib
