### ISSUE TITLE
Request for Integration of HmIP-KRCK (remote control)

### ISSUE THREAD

**Issue by Maxi2509** [hahn-th/homematicip-rest-api#459]
Hi,

i would be happy if you could integrate the remote control HmIP-KRCK.
![2](https://user-images.githubusercontent.com/77342189/191183408-03a813cf-b5a2-4775-b39c-c99e11c585a3.JPG)

Please find below my config file:

[hmip-config_BCF7.zip](https://github.com/hahn-th/homematicip-rest-api/files/9604669/hmip-config_BCF7.zip)

If you have any questions please ask

Best regards,
Maxi

**Comment by hahn-th** [comment]
Hi,
i guess it is not possible, because events are send directly to other devices. So there are no events which are delivered to this library by the API. 
If you want to trigger actions, you can do it anyway without the remote.
