### ISSUE TITLE
Set window open state for thermostate

### ISSUE THREAD

**Issue by chbndrhnns** [hahn-th/homematicip-rest-api#462]
I have some non-HMIP sensors installed on my windows and would like to trigger the open window state from HomeAssistant. Is it possible to write the desired window state to a thermostate so that it changes its temperature to the configured open window temperature?

**Comment by hahn-th** [comment]
I have tried something but it doesn't work. You could fork this lib and try it yourself. Maybe you find a solution.
If you want to lower the temperature, just set the desired value.
