### ISSUE TITLE
Use it with a CCU3

### ISSUE THREAD

**Issue by HarrysLapTimer** [hahn-th/homematicip-rest-api#467]
Is it possible / supported to use the REST API with a CCU3 and locally?
When running hmip_generate_auth_token.py, I get a prompt to enter a SGTIN. I enter my CCU3's SGTIN and nothing happens - the script hangs forever.

**Comment by hahn-th** [comment]
No this is not possible. This lib is for communicating with the Homematic IP Hub. I guess there is something similar out there for the CCU. 
You can use HmIP devices with your CCU. But not the other way i think.

**Comment by HarrysLapTimer** [comment]
Thanks for coming back quickly. Odd that the Homematic systems are so fragmented. I found https://www.homematic-inside.de/software/xml-api which seems to solve my problem by using another REST API by adding an add-on to the CCU3.
