### ISSUE TITLE
Add Device HmIP WUA

### ISSUE THREAD

**Issue by CommanderROR9** [hahn-th/homematicip-rest-api#468]
Hi.

Please add the new Universl 0-10V Dimmer to HmIP Cloud un Home Assistant. Thanks!

**Comment by hahn-th** [comment]
https://github.com/hahn-th/homematicip-rest-api#new-devices-and-config-dump

**Comment by CommanderROR9** [comment]
Working on it. Was about to Upload the dump here, just still figuring it out.

**Comment by CommanderROR9** [comment]
[22a7aafc325119858576b5eb73aa5e94-c3edf9b47ca7ca793f336cae5e4d56e801aaeb1f.zip](https://github.com/hahn-th/homematicip-rest-api/files/9995902/22a7aafc325119858576b5eb73aa5e94-c3edf9b47ca7ca793f336cae5e4d56e801aaeb1f.zip)


I hope I did it right...

**Comment by hahn-th** [comment]
Thx.
In the user manual is written, that you can dim devices, but also there is a ventilationlevel in the data. Can you explain me how this device works? What can you do in the app?

**Comment by CommanderROR9** [comment]
Sure!
This is a pretty nifty Device that offers two 0-10v Outputs (also two 1-10v) which allows Dimming of an LED or control of a Fan or home ventilation system from 0-100%.
The app allows you to configure this as a "Light entity" or as a Fan Entity.
It also has a relay switch connector, but I am bot using that and don't know what it's supposed to be used for 

Is that enough information?

**Comment by hahn-th** [comment]
And you are using just the led dimming with one output? 
Can you for instance use output 1 as led and output 2 as ventilation? I just try to figure out how i have to implement this. 

Befor there is a new version, you have to try it out using the command line interface. Because i can just assume how it works. But we can do it together.

**Comment by CommanderROR9** [comment]
In the app I can only choose one of the options, so either ventilation or light Dimming.
For my usecase a functional light dimmer would be more than enough.
If you need me to test something just ask, but I am not really experienced at using Home Assistant beyond the UI

**Comment by hahn-th** [comment]
These changes are just for this library. HomeAssistant is using this library to talk to the Homematic Hub. But we have to make changes to this lib first and create a new version before it can be implemented into HomeAssistant. I hope this was understandable 😄 

Can you please test my changes? You need python installed on your computer. And then you can install this library with command line tool using command 
`pip install homematicip==1.0.9.post0.dev4`

After that you can go on with the described commands here:
https://github.com/hahn-th/homematicip-rest-api#usage

Register your hub, search your device and call commands
`python hmip_cli.py -d <id-from-device-list> --set-dim-level 0.5 --channel 1`

You could test --set-dim-level, --turn-on and --turn-off. 
If you have errors. please post them here. 

If you have trouble, contact me on discord.

**Comment by CommanderROR9** [comment]
Thanks.

I will try and find time to attempt this. Pretty busy week for me, so no
promises, but I will try and then keep you posted.

hahn-th ***@***.***> schrieb am Mo., 14. Nov. 2022, 08:10:

**Comment by CommanderROR9** [comment]
Hi there again,

Sorry that I didn't send any more replies, had a crazy week.
Thing is...I decided to go Homematic IP Local with the USB Stick thingy,
and in that configuration the Universal Actor just works out of the box, so
problem solved for me.
If I ever find myself with too much free time on my hands I might still see
how to get this working with the Homematic Cloud, but it's no longer a
priority for me...sorry.

Roland Rohde ***@***.***> schrieb am Mo., 14. Nov. 2022, 09:57:

**Comment by hahn-th** [comment]
You could help the community and appreciate my work if you test it anyway.
