### ISSUE TITLE
HmIP-eTRV-E opening angle and actual temperature missing 

### ISSUE THREAD

**Issue by horstvogel** [hahn-th/homematicip-rest-api#471]
for the HmIP-eTRV-E opening angle and actual temperature missing in home assitstant are missing

**Comment by hahn-th** [comment]
I can't find a value for opening angle in my testdata. Can you please provide your anonizmed config as described here: https://github.com/hahn-th/homematicip-rest-api#new-devices-and-config-dump
You can also download a config in home-assistant via service "dump hap config".

**Comment by horstvogel** [comment]
sorry i don't understand that. Which CLI do you have to use? Home Assistant's? The data was probably not transferred from the integration of home matic ip to home assistant? maybe there is a video to use this?
thanks!

**Comment by hahn-th** [comment]
Deinem Namen nach zu urteilen sprichst du deutsch?
Was genau meinst du mit opening angle? Wie offen das Ventil ist?

**Comment by horstvogel** [comment]
Richtig, danke! Der Öffnungswinkel vom Ventil wird nicht angezeigt. Weiter wird die Temperatur nicht angezeigt. Bei den anderen Thermostaten funktioniert das bei mir, ich habe Basic, das "normale" und halt 3 x EVO, Bei den Evos fehlen die Informationen

**Comment by hahn-th** [comment]
Der EVO scheint auch noch nicht im HomeAssistant drin zu sein. Es gibt auch einen offenen Issue dafür 
https://github.com/home-assistant/core/issues/79252
Ich baue das mal ein. 👍

**Comment by horstvogel** [comment]
Ok, steuern kann ich das Thermostat allerdings schon. Benötigst Du nun noch was von mir? 
Was ich dann hoffentlich auch liefern kann ;-) 
Danke! 
ok, den ganzen link von Dir durchgelesen, jetzt verstanden, die anderen haben die gleichen Funktionen wie ich. 
Sorry

**Comment by hahn-th** [comment]
Kein Problem. Ne mehr brauche ich nicht. Bin gerade dran. 👍 ich mache hier zu, da das ja zu Home Assistant gehört.

**Comment by horstvogel** [comment]
Ok, wenn ich das jetzt richtig alles verfolgt habe, dann hast Du das Evo schon integriert. Wie mache ich dann eigentlich ein Update, damit ich das EVO jetzt "richtig" nutzen kann? 

https://www.home-assistant.io/integrations/homematicip_cloud
Ich habe das dann ja über den Link "installiert", taucht dann über Einstellungen --> Integrationen --> HomematicIP Cloud dann hier eine neue Version auf?

Vielen Dank!

**Comment by hahn-th** [comment]
Ne, es wird gehen, wenn 1. meine Änderungen in das Programm mit aufgenommen werden und 2. wenn dann eine Version draussen ist. Wenn du Glück hast geht es ganz schnell, wenn du Pech hast, kann es eine lange dauern (Monate)

**Comment by horstvogel** [comment]
Ok, mit Programm meinst Du home assistant. Kann man das irgendwo verfolgen, ob das wann dann übernommen worden ist? Oder wenn das https://github.com/home-assistant/core/pull/82757   Ticket geschlossen ist, dann wurde es ins Home Assistant aufgenommen und würde dann mit der nächsten Version rauskommen?
Danke!
