### ISSUE TITLE
[NEW DEVICE] HmIPW-WRC6, HmIPW-FALMOT-C12, HmIPW-WTH, HmIPW-FIO6, HmIPW-SPI, HmIPW-DRBL4, HmIPW-SMI55

### ISSUE THREAD

**Issue by Danzelot123** [hahn-th/homematicip-rest-api#478]
Please add some more Homematic IP Wired Devices, like the HmIPW-WRC6, my config file contains:

HmIPW-FALMOT-C12
HmIPW-WTH
HmIPW-FIO6
HmIPW-SPI
HmIPW-DRBL4
**HmIPW-WRC6** <-- the latest 6channel switch (with 6 leds)
HmIPW-SMI55

Here is my config:
[hmip-config.json](https://gist.github.com/Danzelot123/9143d7a6cee7f2f5f0a24a354f8d5b4a)

Thanks for your work.

**Comment by hahn-th** [comment]
Can you test the devices after implementation via commandline cli?

**Comment by Danzelot123** [comment]
Yes, sure, that's the least I can do if you take the trouble to implement it.

**Comment by hahn-th** [comment]
Do you know, what the OPTICAL_SIGNAL_CHANNEL does? It belongs to the WRC6 device. Something with the LEDs maybe? What are the LEDs doing? There are 6 channels.

**Comment by Danzelot123** [comment]
Yes, in addition to wireless HmIp-WRC6 the wired version has 6 LEDs to have feedback per button.
Each LED can be program (options available via app):

on:              true | false
dimLevel:    0.0 - 1.0
simpleRGBColorState:   GREEN | BLACK | BLUE | TURQUOISE | PURPLE | RED |  YELLOW | WHITE
opticalSignalBehaviour: ON | BLINKING_MIDDLE | FLASH_MIDDLE | BILLOW_MIDDLE | OFF   

Looks like a NotificationLightChannel with an addition opticalSignalBehaviour parameter.
Basically you can turn on a LED, set DimLevel, Color and the behaviour: like blinking or pulsing etc. 

(There should a 7. channel, this has to be a group channel to control all 6 LEDs at once)

**Comment by hahn-th** [comment]
Hey :) Bis auf HmIPW-SPI sind alle drin. Du könntest den Branch 478 (https://github.com/hahn-th/homematicip-rest-api/tree/478) mal clonen und testen.

**Comment by Danzelot123** [comment]
Bin beim testen, erkennen und anzeigen sieht erstmal gut aus :)
 
Ob das Steuern klappt muss ich erst noch was für zusammen coden da ich über die cli nur die Ausgänge vom FIO6 setzen konnte.  


Folgende Devices/Channels werden neben den PRESENCE_DETECTOR noch als Warning ausgegeben:
**HMIPW-SPI**
2023-01-17 08:35:13,714 - homematicip.base.enums - WARNING - 'WIRED_PRESENCE_DETECTOR_INDOOR' isn't a valid option for class 'DeviceType'
2023-01-17 08:35:13,715 - homematicip.home - WARNING - There is no class for device 'WIRED_PRESENCE_DETECTOR_INDOOR' yet


**HmIPW-DRAP:**
2023-01-17 08:35:13,698 - homematicip.base.enums - WARNING - 'WIRED_DIN_RAIL_ACCESS_POINT' isn't a valid option for class 'DeviceType'
2023-01-17 08:35:13,699 - homematicip.home - WARNING - There is no class for device 'WIRED_DIN_RAIL_ACCESS_POINT' yet
2023-01-17 08:35:13,774 - homematicip.base.enums - WARNING - 'ACCESS_CONTROLLER_WIRED_CHANNEL' isn't a valid option for class 'FunctionalChannelType'
2023-01-17 08:35:13,774 - homematicip.device - WARNING - There is no class for functionalChannel 'ACCESS_CONTROLLER_WIRED_CHANNEL' yet


**HmIPW-WRC6**
2023-01-17 08:35:13,757 - homematicip.base.enums - WARNING - 'OPTICAL_SIGNAL_GROUP_CHANNEL' isn't a valid option for class 'FunctionalChannelType'
2023-01-17 08:35:13,767 - homematicip.device - WARNING - There is no class for functionalChannel 'OPTICAL_SIGNAL_GROUP_CHANNEL' yet

**Comment by hahn-th** [comment]
> Ob das Steuern klappt muss ich erst noch was für zusammen coden da ich über die cli nur die Ausgänge vom FIO6 setzen konnte.

Welche Aktionen genau bei welchen Geräten? Dann kann ich die CLI anpassen.


> **HmIPW-DRAP:** 2023-01-17 08:35:13,698 - homematicip.base.enums - WARNING - 'WIRED_DIN_RAIL_ACCESS_POINT' isn't a valid option for class 'DeviceType' 2023-01-17 08:35:13,699 - homematicip.home - WARNING - There is no class for device 'WIRED_DIN_RAIL_ACCESS_POINT' yet 2023-01-17 08:35:13,774 - homematicip.base.enums - WARNING - 'ACCESS_CONTROLLER_WIRED_CHANNEL' isn't a valid option for class 'FunctionalChannelType' 2023-01-17 08:35:13,774 - homematicip.device - WARNING - There is no class for functionalChannel 'ACCESS_CONTROLLER_WIRED_CHANNEL' yet

Mit dem AP funktioniert aber auch alles wie gehabt? Dann baue ich den noch ein.

**Comment by hahn-th** [comment]
Ich hab dir mal die Funktion set_rgb_dim_level zum WGC Button hinzugefügt. Probier das mal aus. Falls das nicht funktioniert und die dich mit SSL Proxy auskennst, könntest du das mal analysieren, was da wie aufgerufen wird.

**Comment by Danzelot123** [comment]
Es geht mir genau um das setzen der LEDs am WRC6 (sowie der Ausgänge des FIO6 was bereits funktioniert):
Für den WRC6 gibt es: Result from channel 7: {"errorCode": "FEATURE_NOT_SUPPORTED"}

Zum setzten von opticalSignalBehaviour oder simpleRGBColorState:
**/hmip/device/control/setOpticalSignal**
```
{
    "channelIndex": 7,
    "deviceId": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "dimLevel": 1.01,
    "opticalSignalBehaviour": "BILLOW_MIDDLE",
    "simpleRGBColorState": "PURPLE"
}
``` 
*Hier ist dimLevel zwar vorhanden aber immer auf 1.01

Und für das DimLevel:
**/hmip/device/control/setDimLevel**
```
{
    "channelIndex": 7,
    "deviceId": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "dimLevel": 0.5
}
```

**Comment by hahn-th** [comment]
Beide Aufrufe sind drin.

**Comment by Danzelot123** [comment]
Sehr schön. Funktioniert auch, soweit ich das sagen kann, alles ;-)

Anmerkung um es noch Runder zu machen: 

- Der WRC2 hat keine LEDs, nur der WRC6 - der WiredPushButton in devices unterscheidet da aktuell noch nicht. 

- Falls man es im WRC6 abfangen möchte: die Kanäle dürfen nur zwischen >= 7 und <= 13 liegen.

- Für die LED Kanäle wird auch "device/control/setSwitchState" (genau wie beim switch) unterstützt - das hatte ich übersehen.

Zur Bedienung:
_Die dimLevel=1.01  bei setOpticalSignal funktioniert auch mit 0..1 (auch wenn ich das so nicht vorher beobachten konnte). Bei 1.01 bleibt der Wert halt ungeändert.

Bei Kanal 13 werden alle 6 LEDs gleichzeitig angesprochen und übersteuern die einzelnen Kanäle, schaltet man 13 aber wieder ab, werden wieder die individuellen Werte verwendet._

**DANKE!**

**Comment by hahn-th** [comment]
set_switch_state ist drin mit turn_on und turn_off. Der Rest ist egal. Ich wollte sowieso umbauen, dass die Channels die Funktionen haben und nicht mehr die devices. Denn um die geht es ja und für die wird auch die Aktion ausgeführt. Die LED calls gelten z.B. nicht für die single_key_channels. Und dann fallen langfristig auch spezielle devices weg, denn dann reicht ein generisches.

**Comment by hahn-th** [comment]
Meld dich doch mal unter homematicip-rest-api@thomas-hahn.org oder in Discord.
