### ISSUE TITLE
Full Support for HMIP-DSD-PCB

### ISSUE THREAD

**Issue by saschaabraham** [hahn-th/homematicip-rest-api#479]
Hello,

the Device is shown in HA, but there are no properties available. Which means, the device is not usable within HA.

Message withing HA log:
```
Logger: homematicip.home
Source: components/homematicip_cloud/hap.py:256
First occurred: 6. Januar 2023 um 11:54:32 (1 occurrences)
Last logged: 6. Januar 2023 um 11:54:32

There is no class for device 'DOOR_BELL_CONTACT_INTERFACE' yet

```

[Dump of the Configfile](https://gist.github.com/saschaabraham/f574e9547bdfcd3aa9aaba5c179ca8d4)

**Comment by saschaabraham** [comment]
Sorry, the link above was not korrekt, I think, this should be the right one : [ConfigFile](https://gist.github.com/saschaabraham/7f6be1b2d955da9e6d93f752c0cf21c6)

**Comment by saschaabraham** [comment]
Is there any more information needed to implement his sensor?

**Comment by hahn-th** [comment]
Its in this lib now. But the implementation in HA has to do somebody else because i am busy

**Comment by aschobba** [comment]
@saschaabraham I only the Battery Status in HA atm. 
I was checking a bit the code and did some tests.
**Outcome of the Tests:**
1. Channel 2 holds window state but looks it’s it is not changing when I'm using my doorbell
2. I also see new events when I press the doorbell

Looks to me like no way to get the doorbell state in HA?

**Comment by aschobba** [comment]
```
                "1": {
                    "actionParameter": "NOT_CUSTOMISABLE",
                    "binaryBehaviorType": "NORMALLY_CLOSE",
                    "channelRole": "DOOR_BELL_INPUT",
                    "corrosionPreventionActive": false,
                    "deviceId": "xxxxxxxxxxxxxx",
                    "doorBellSensorEventTimestamp": 1685186582800,
                    "eventDelay": 0,
                    "functionalChannelType": "MULTI_MODE_INPUT_CHANNEL",
                    "groupIndex": 1,
                    "groups": [
                        "00000000-0000-0000-0000-000000000024",
                        "00000000-0000-0000-0000-000000000093"
                    ],
```

doorBellSensorEventTimestamp holds the information at which time the doorbell was ringing the last time. 
I was able to load it in HA, but only updates the value in HA when the integration reloaded.
I think this is because there are no events popping up when I'm ringing the bell. Normally, I see on every change, an event.
@hahn-th Do see any chance to get this running?

**Comment by kapkinn** [comment]
Hello,
did anybody find a smart way to make use of the doorbell sensor in HA?

I am not a development expert, so cannot contribute with in-depth knowledge.
Sofar I do this, but pls let me know if there is a better/smarter way.
Sorted out the issue the rude way: I do have a HM-IP power plug which is in just acting as a signal repeater.
1. I created an automation in HM: the doorbell is providing an impulse of 1 sec switching this power plug for a second to ON.
2. HA is now using the switch state of this device listening on a change of this to act as a trigger in HA. Works without recognizing a delay and in the last weeks also absolutely reliable.
For sure not elegant and sophisticated but maybe a workaround for others as well.

**Comment by saschaabraham** [comment]
You can create a routine within alexa to switch on some switch within HA using the doorbell event as reigger. So there is no mechanical element involved, so no wear out.

**Comment by aschobba** [comment]
Same for me, I'm now triggering a script in HA if with an Alexa Routine.
