### ISSUE TITLE
New "HmIP-eTRV-2 I9F" not usable?

### ISSUE THREAD

**Issue by IXArcanumXI** [hahn-th/homematicip-rest-api#482]
Hey everyone.

I'm not sure if I'm just dumb or if this device isn't working in HomeAssistant at the moment. I just bought a new HmIP-eTRV-2 thermostat from Amazon. It identifies itself as "HmIP-eTRV-2 I9F", which is, according to a German Homematic forum, a new version of the eTRV-2 with a new chipset, because the old chipset isn't on the market anymore (https://homematic-forum.de/forum/viewtopic.php?f=58&t=76587).

HomeAssistant recognizes the device, but I can't control it. It just says "unavailable", while the "normal" eTRV-2 works just fine:

![image](https://user-images.githubusercontent.com/10199332/215574801-57f555ee-692e-49a2-964a-ceba3d9421f5.png)

I'll attach my HAP dump in order to get this device integrated. If I'm just too dumb, please tell me ^^
[hmip-config_B297.json.txt](https://github.com/hahn-th/homematicip-rest-api/files/10539189/hmip-config_B297.json.txt)

EDIT: just checked - the status update works fine. If I turn up the temperature, HomeAssistant get's the new heating status and temperature, so still not sure if something else is wrong with my setup:
![image](https://user-images.githubusercontent.com/10199332/215579016-a99bd052-34d5-42c3-9be0-f597b56bc34e.png)

**Comment by hahn-th** [comment]
Its because of the name. Maybe, its in the next version of HomeAssistant.

**Comment by IXArcanumXI** [comment]
Thanks a lot, appreciate your work very much!

**Comment by IXArcanumXI** [comment]
Several HA-updates later, still not usable :(

**Comment by hahn-th** [comment]
Funktioniert bei mir. Habe Tests zu deinem Gerät hinzugefügt. Da musst du dir wohl HomeAssistant anschauen. Ich habe nämlich viel zu tun gerade.

**Comment by IXArcanumXI** [comment]
Can confirm it's working now! Had to deinstall and reinstall HMIP-integration to get it working. Don't know why, but doesn't matter. Thanks again @hahn-th ! Danke dir!
