### ISSUE TITLE
HmIP-BS2

### ISSUE THREAD

**Issue by botfixer** [hahn-th/homematicip-rest-api#483]
Is it possible to add HmIP-BS2 as new device?

I had a look on this:

https://github.com/hahn-th/homematicip-rest-api/issues/450

which seems to be a similar device, but the link are not available any more.
As far as i know, the elv product is the same thing, the only difference seems to be, that the ELV thing is a kit.

Should i provided a json dump?

Edit:
[HMip-BS2.txt](https://github.com/hahn-th/homematicip-rest-api/files/10707463/HMip-BS2.txt)

**Comment by botfixer** [comment]
BS2 Dump attached.

**Comment by hahn-th** [comment]
Der sollte schon funktionieren.

**Comment by Marc9608** [comment]
Hallo, ich versuche ebenfalls den BS2 Aktor von HomematicIP in meine Homebridge zu integrieren. Könnt ihr mir da behilflich sein?

**Comment by hahn-th** [comment]
Wie gesagt, das Ding sollte schon funktionieren. Homebridge kenne ich leider nicht.
