### ISSUE TITLE
Homematic IP CO2-Sensor HmIP-SCTH230 Interation

### ISSUE THREAD

**Issue by bike4funmiko** [hahn-th/homematicip-rest-api#484]
Hello,

can you please integrate the CO2 sensor from Homematic IP -> HmIP-SCTH230

BR
Michael

[hmip-config_CE10.txt](https://github.com/hahn-th/homematicip-rest-api/files/10763151/hmip-config_CE10.txt)

**Comment by hahn-th** [comment]
But you have to implmement the device in homeassistant yourself. I am busy.
