### ISSUE TITLE
HomematicIP: There is no class for device 'DOOR_BELL_BUTTON' yet

### ISSUE THREAD

**Issue by wela1602** [hahn-th/homematicip-rest-api#485]
I integrated a new HomeMatic-IP device into my system. It is a battery driven dor-bell-button '**HmIP-DBB**'. Now a see the following errors in my Home Assistant logfile:
- 'There is no class for device 'DOOR_BELL_BUTTON' yet'
   _Logger: homematicip.home
   Source: components/homematicip_cloud/hap.py:258_
- 'DOOR_BELL_BUTTON' isn't a valid option for class 'DeviceType'
   _Logger: homematicip.base.enums
   Source: components/homematicip_cloud/hap.py:258_

The errorrs occure once after restart of Home Assistant.

dump of my access point configuration:
[hmip-config_9C0C.zip](https://github.com/hahn-th/homematicip-rest-api/files/10775081/hmip-config_9C0C.zip)

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

Help is welcome,
Thank You

**Comment by hahn-th** [comment]
Somebody else has to implement the device in HA cause i am busy

**Comment by wela1602** [comment]
Who else is able to do the implementation? Where else can I place my request?
Thank you.
