### ISSUE TITLE
New Device - Klingelsignalerkennung HmIP-DSD-PCB

### ISSUE THREAD

**Issue by svensoltmann** [hahn-th/homematicip-rest-api#486]
Hello, I found in my Log-Files this Info: "There is no class for device 'DOOR_BELL_CONTACT_INTERFACE' yet"

Here is my dump file: 
[hmip-config_A4D7.zip](https://github.com/hahn-th/homematicip-rest-api/files/11068716/hmip-config_A4D7.zip)

thanks for your work,

Sven

**Comment by saschaabraham** [comment]
This is already done in #479
