### ISSUE TITLE
Some basic info about the API

### ISSUE THREAD

**Issue by thorek** [hahn-th/homematicip-rest-api#488]
Great work, re-engineering this! 

Unfortunately I can't and don't want to use python in an integration scenario with my PV system. Is there any way you can share some basic ideas how to call the API directly via https? I guess it comes down to finding / calculating the AUTH values. The rest is basic JSON handling, right? 

Any help is greatly appreciated.

**Comment by hahn-th** [comment]
“Truth can only be found in one place: the code.”
    – Robert C. Martin

Have a look in the code.

**Comment by thorek** [comment]
Nothing is to be expected by an open source developer. He puts his efforts when and where he wants. We, the community, the benefiters, may only say our thanks. And I mean it. 

Nothing can be expected by an open source developer, except for not being rude. In that you failed.

**Comment by hahn-th** [comment]
I am sorry about that. That wasnt my intention. Sometimes people think i am waiting for them to fulfill their needs. Sorry about that!
Have a look into the file hmip_generate_auth_token.py. 
It is just few lines of code you can adapt where easy.

**Comment by thorek** [comment]
Thanks, man. It takes greatness for a man to say sorry. Appreciate it.
