### ISSUE TITLE
Optional Device Feature 'IOptionalFeatureControlsMountingOrientation' is not yet supported

### ISSUE THREAD

**Issue by svensoltmann** [hahn-th/homematicip-rest-api#489]
Hello, I found in my Log-Files this many Warnings : "Optional Device Feature 'IOptionalFeatureControlsMountingOrientation' is not yet supported". Unfortunately I don't know which device it belongs to.

---//---
Logger: homematicip.device
Source: components/homematicip_cloud/hap.py:189
First occurred: 15:37:22 (3 occurrences)
Last logged: 15:37:22

Optional Device Feature 'IOptionalFeatureControlsMountingOrientation' is not yet supported

and: 

Logger: homematicip.device
Source: components/homematicip_cloud/hap.py:258
First occurred: 15:37:21 (3 occurrences)
Last logged: 15:37:21

Optional Device Feature 'IOptionalFeatureControlsMountingOrientation' is not yet supported
---//---

My Dump-File: 
[hmip-config_A4D7.zip](https://github.com/hahn-th/homematicip-rest-api/files/11359331/hmip-config_A4D7.zip)

Thanks for the help.

Sven

**Comment by hahn-th** [comment]
That should be fixed with the latest version.
