### ISSUE TITLE
get_current_state() throws 'EXTERNAL' isn't a valid option for class 'DeviceType'

### ISSUE THREAD

**Issue by codac** [hahn-th/homematicip-rest-api#490]
Running the home.get_current_state() throws 'EXTERNAL' isn't a valid option for class 'DeviceType'.
Seems like needs to be added?!

**Comment by hahn-th** [comment]
Upgrade to the latest version

**Comment by codac** [comment]
I did (`pip install -U homematicip` and `pip install --upgrade homematicip`) and the exception still remains.

**Comment by hahn-th** [comment]
Can you please append your config as txt or json file. https://github.com/hahn-th/homematicip-rest-api#new-devices-and-config-dump

Please describe how you are using the lib. Because i fixed that problem a while ago.

**Comment by codac** [comment]
I'm running the following code:

```
def main():

    print (splashScreen)

    ledStartupSequence ()

    errorLog = open("/home/pi/r2d2-hmip-error.log","w")

    while True:

        try:
            global led3DeviceIsOffline
            global led4DeviceIsOffline
            global led5DeviceIsOffline

            # delete old datasets from database
            deleteOldDatasets ()

            # read status of devices and write to database
            global home
            home.get_current_state()
```
The "home.get_current_state() throws the error.

Here is the config:
https://gist.github.com/codac/83331d0b0d1f8c0488287966438761bc

**Comment by hahn-th** [comment]
Works like a charm for me. 
You have to update to the latest version. I guess, you're not updating the sources, you are using for your script.  But you have to find that out by yourself. I think, you can close the issue.
