### ISSUE TITLE
Can't set shutter level for HmIPW-DRBL4

### ISSUE THREAD

**Issue by karungarolongo** [hahn-th/homematicip-rest-api#499]
I get an error `Can't set shutter level of device xxxxxxxxxxxx of type WIRED_BLIND_4` when I try to control the blinds via hmip_cli.py.
Is this supported? Is it possible to set shutter and slats individually?
Thanks in advance!

**Comment by hahn-th** [comment]
Fixed with the next version. You can select the target channel with the --channel argument. Multiple channels are also allowed.
