### ISSUE TITLE
Homematic IP HmIP-DSD-PCB Klingelsignalsensor (Doorbell- or Ringing Signal Sensor)

### ISSUE THREAD

**Issue by kapkinn** [hahn-th/homematicip-rest-api#501]
Dear experts,

I'm struggling to get this Homematic IP device working correctly: HmIP-DSD-PCB
The device is detecting a ringing bell (Door, Phone, ...) and sending a short "key press"/trigger event.
It does work fine in Homematic IP (access point), but in Home Assistant it just shows up with one sensor: state of the own battery.

Is this an issue in my installation, or is the device not fully supported by HA?
If so, any plans to integrate this device? 

Any advice how to fix this?

many thx in advance.

**Comment by hahn-th** [comment]
The direct way is not possible. But have a look at this issue:
https://github.com/hahn-th/homematicip-rest-api/issues/479

Maybe ask there, if they found a proper solution.

**Comment by kapkinn** [comment]
Sorted out the issue the rude way: I do have a HM-IP power plug which is in just acting as a signal repeater.
1. I created an automation in HM: the doorbell is providing an impulse of 1 sec switching this power plug
2. HA is now using the switch state of this device listening on a change of this to act as a trigger in HA. Works without recognizing a delay and in the last weeks also absolutely reliable.
For sure not elegant and sophisticated but maybe a workaround for others as well.

**Comment by saschaabraham** [comment]
> 1. I created an automation in HM: the doorbell is providing an impulse of 1 sec switching this power plug

You should use something like the boost function of a thermostat, so there is no wear of the plug. I think switching this on for one second is not good for the lifetime. 
I use the boost function of a thermostat in the living room. HomeAssistant recognizes the boost activation and cancels the boost immediatly. So the thermostat ist not moving at all, Another nice option is, that the boost cancels itself after some time, if HA fails to cancel this.
