### ISSUE TITLE
Set Logger Level - Not an issue

### ISSUE THREAD

**Issue by cn-schuh** [hahn-th/homematicip-rest-api#504]
Hi, 
first of all i like the API. Currently i monitoring my HIP devices using Python. 
My question: Would it be possible to set or deactivate the logging level within Python? I guess this isn't implemented.
For sure i could do this within each of the *.py manually but this might not be effective.

I am aware warning like "ENERGY' isn't a valid option for class 'FunctionalHomeType" or "Optional Device Feature 'IOptionalFeatureFilteredMulticastRouter' is not yet supported" are helpful, but not when i can ignore those.

Best Regards 
Chris

**Comment by hahn-th** [comment]
Hi,
if you are using cli, you can add the argument --debug-level with param 10 (debug), 20, 30, 40 or 50 (critical).

In code you can set the log level via `logging.basicConfig(level=x)`

I hope this helped. Regarding the warnings: in the next time i will fix the error messages.

**Comment by cn-schuh** [comment]
Great and Thank You. This helps. Another question when i can? HmIP-SWDO-2 are there any plans to get it supported in the future? 
Currently i am monitoring all of my HIP devices, really great library You developed. Thank You so much!

**Comment by hahn-th** [comment]
Open a new Issue and post your anonymized config there and i will implement it.
