### ISSUE TITLE
TOGGLE_GARAGE_DOOR IS NOT allowed for channel DOOR_CHANNEL

### ISSUE THREAD

**Issue by Rosi1981** [hahn-th/homematicip-rest-api#507]
hi all,
i'm trying to apply the toggle door switch to a HmIP-MOD-HO Garagentor from Hörmann which results in:

hmip_cli.py -d 3014F711A000241D89B00174  --toggle-garage-door
WARNING:root:TOGGLE_GARAGE_DOOR IS NOT allowed for channel DOOR_CHANNEL
2023-11-20 14:57:01,775 - root - WARNING - TOGGLE_GARAGE_DOOR IS NOT allowed for channel DOOR_CHANNEL
TOGGLE_GARAGE_DOOR is not supported by channel DOOR_CHANNEL (Index: 1)

i can switch channel 0 which results in:

hmip_cli.py -d 3014F711A000241D89B00174 --channel 0 --toggle-garage-door
WARNING:root:TOGGLE_GARAGE_DOOR IS NOT allowed for channel DEVICE_BASE
2023-11-20 14:56:51,905 - root - WARNING - TOGGLE_GARAGE_DOOR IS NOT allowed for channel DEVICE_BASE
TOGGLE_GARAGE_DOOR is not supported by channel DEVICE_BASE (Index: 0)

Any hints?

**Comment by hahn-th** [comment]
toggle-garage-door is just for HmIP-WGC. I have added --send-door-command argument. You could use OPEN, CLOSE, STOP or PARTIAL_OPEN as parameters. 
Example: -d deviceid --send-door-command OPEN

**Comment by hahn-th** [comment]
btw: to test before version 1.0.17 is released, you can use the prerelease: pip install homematicip==1.0.16.post0.dev5
