### ISSUE TITLE
New Device: Interface for Smart Meters

### ISSUE THREAD

**Issue by cyb3rforce** [hahn-th/homematicip-rest-api#509]
New device for Homematic IP: Interface for smart meters
Measurements for power,energy and gas smart meters.

HmIP-ESI-IEC

Starting in line 4650 of the dump.
Sensor values in line 4738 of the dump.

[hmip-config_7B9B.json](https://github.com/hahn-th/homematicip-rest-api/files/13535991/hmip-config_7B9B.json)

BR

**Comment by FlipFlopFlippi** [comment]
Also waiting for support of this device...find my dump below!
[hmip-config_32CB.json](https://github.com/hahn-th/homematicip-rest-api/files/13654231/hmip-config_32CB.json)
Starting in line 6192 as far as i can see
BR & thank you!

**Comment by hahn-th** [comment]
I am quite busy at the moment. 
Are there any interactions with the device or can you just read the energy values?

**Comment by cs42** [comment]
There are no interactions with the device after setup. You can just read the energy and power values.

**Comment by cyb3rforce** [comment]
No interaction at all.
Its only a read out of the sensor values and the new sensor type ES_IEC:
I suspect that the data value 1 indicates that the chip used supports more than one sensor. But the current sensor sold by Homematic only has one connection.

`"1": {
                    "channelRole": "ENERGY_SENSOR",
                    "connectedEnergySensorType": "ES_IEC",
                    "currentGasFlow": null,
                    "currentPowerConsumption": 512.0,
                    "deviceId": "3014F7110000000000000036",
                    "energyCounterOne": 5273.2153,
                    "energyCounterOneType": "ENERGY_COUNTER_USAGE_HIGH_TARIFF",
                    "energyCounterThree": null,
                    "energyCounterThreeType": "UNKNOWN",
                    "energyCounterTwo": 3256.1887,
                    "energyCounterTwoType": "ENERGY_COUNTER_USAGE_LOW_TARIFF",
                    "functionalChannelType": "ENERGY_SENSORS_INTERFACE_CHANNEL",
                    "gasVolume": null,
                    "gasVolumePerImpulse": 0.01,
                    "groupIndex": 1,
                    "groups": [
                        "00000000-0000-0000-0000-000000000051"
                    ],
                    "impulsesPerKWH": 10000,
                    "index": 1,
                    "label": "",
                    "supportedOptionalFeatures": {
                        "IOptionalFeatureCounterOffset": false,
                        "IOptionalFeatureCurrentGasFlow": false,
                        "IOptionalFeatureCurrentPowerConsumption": true,
                        "IOptionalFeatureEnergyCounterOne": true,
                        "IOptionalFeatureEnergyCounterThree": true,
                        "IOptionalFeatureEnergyCounterTwo": true,
                        "IOptionalFeatureGasVolume": false,
                        "IOptionalFeatureGasVolumePerImpulse": false,
                        "IOptionalFeatureImpulsesPerKWH": false
                    }
                }`

**Comment by ChristophCaina** [comment]
This device is the IP counterpart of the old Homematic HM-ES-TX-WM, which provides a plattform to connect different types of reader - for various types of meter.

The ES-IEC is one of those readers , others are: ES-Gas2, ES-Fer, ES-LED
I could imagine, that the HmIP would also support those other readers - maybe, with upcomming firmware updates.
I already found some topics in the ELV Forum, where people implemented this device in their CCU / Raspberry Matic, and it seems, that the device already supports Gas-Meters or at least does recognize other readers.

The ES-IEC is the default one that comes with the product.

**Comment by hahn-th** [comment]
There is the ENERGY_SENSORS_INTERFACE_CHANNEL functional channel. Channel Role is ENERGY_SENSOR. I guess, if there are other sensors for other meters there will be another FunctionalChannelType or ChannelRole. So if somebody includes the unknown sensor into his setup, there will be an error message, that the new FunctionalChannel is not supported. 
Thats the way it typically works.
