### ISSUE TITLE
Support for Homematic HmIP-ESI-IEC

### ISSUE THREAD

**Issue by FlipFlopFlippi** [hahn-th/homematicip-rest-api#511]
Hello everyone,

I was very happy about the new Homematic IP product "hmip-esi-iec", as I now have an energy meter that is directly connected to the grid operator's consumption meter, integrates with HMIP and is battery powered, so I don't need a socket near the meter box. Unfortunately I don't see the device in the Home Assitant, as I see it in the config-dump, the information is contained around line 6280. Can you add the device to the extension? 

Thank you, 
Your Flippi
[hmip-config_32CB.json](https://github.com/hahn-th/homematicip-rest-api/files/13654218/hmip-config_32CB.json)

**Comment by FlipFlopFlippi** [comment]
Just saw that there is also the same issue

**Comment by hahn-th** [comment]
I have released v1.1 including that device
