### ISSUE TITLE
bump latest version to homeassistant core

### ISSUE THREAD

**Issue by ChristophCaina** [hahn-th/homematicip-rest-api#517]
HomeAssistant Core still needs to be updated to the latest version of this module...
I would do this by myself - but I can't provide the required tests for the PR :-(

**Comment by ChristophCaina** [comment]
ref:
1. https://github.com/home-assistant/core/issues/108775
2. https://github.com/home-assistant/core/issues/109055

**Comment by hahn-th** [comment]
Hi. I close this. PR is open for HmIP-ESI-IEC.
