### ISSUE TITLE
Please add new device "HmIP-ESI-GAS" (new gas energy sensor)

### ISSUE THREAD

**Issue by P4TR1CK-V3LT3** [hahn-th/homematicip-rest-api#518]
It would be amazing if it's possible to add the new gas sensor.

This consists of the energy sensor interface "HmIP-ESI" and the gas sensor "ES-GAS-2"

Attached the IMHO necessary config-dump parts.

Thanks in advance!

[hmip-config_9D10.json](https://github.com/hahn-th/homematicip-rest-api/files/14397132/hmip-config_9D10.json)

**Comment by P4TR1CK-V3LT3** [comment]
https://github.com/home-assistant/core/issues/109055#issuecomment-2003722178

**Comment by hahn-th** [comment]
PR is open 👍
