### ISSUE TITLE
'ENERGY' isn't a valid option for class 'GroupType'

### ISSUE THREAD

**Issue by Userunknown19** [hahn-th/homematicip-rest-api#520]
Hello,
I find the following messages in my HomeAssitant log files for HomematicIP Cloud:

```
2024-03-11 10:53:38.079 WARNING (MainThread) [homematicip.base.enums] 'ENERGY' isn't a valid option for class 'GroupType'
2024-03-11 10:53:38.079 WARNING (MainThread) [homematicip.home] There is no class for group 'ENERGY' yet
```

I also noticed that there are no entities available for the device 'HmIP-ESI' for the energy consumption, possibly because of the error described above?
I use Home Assistant Operating System on a Raspebrry PI, as far as I know all updates are installed:
Core 2024.3.0
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240306.0

Can I fix the error myself or is this possibly a known problem?
Thank you very much

**Comment by Userunknown19** [comment]
Hello,
the error is still present even with the new versions/updates that have been released in the meantime.
Does anyone have an idea or a hint for me?
Currently installed versions:

- Core 2024.4.2
- Supervisor 2024.04.0
- Operating System 12.1
- Frontend 20240404.1

Thanks

**Comment by hahn-th** [comment]
Can you please provide your config dump?

**Comment by Userunknown19** [comment]
[hmip-config_20210421_8263.json](https://github.com/hahn-th/homematicip-rest-api/files/15052391/hmip-config_20210421_8263.json)
Hello,
config dump attached.
If I can somehow solve the problem myself let me know.
Thank you
