### ISSUE TITLE
HMIP-BSL with new Functions after Firmwareupgrade

### ISSUE THREAD

**Issue by Timer2000** [hahn-th/homematicip-rest-api#523]
Hello,

the HMIP-BSL has an new Firmware with a new Function to control the signal behavior (permanently,flash,pulsating,lightning).

The Problem is it is not possible to set the light without this new parameter. After set the light it is necessary to set the signal behavior in the Homemativ IP App.

Please put the new Function in the API

Thx
Timer

**Comment by hahn-th** [comment]
Good to know. The problem is: i dont own the device. Somebody has to find out how the function has changed, what are new parameters and so on. 
This has to be done with a proxy. I had the same discussion here: #492 
Read it and give me the information i need.

**Comment by SebeSebe** [comment]
Hi,
I habe the same issue after firmware upgrade.
HMIP added a new parameter opticalSignalBehaviour to channel 2 and 3 of HMIP-BSL. Valid values are: ON, BLINKING_MIDDLE, BILLOW_MIDDLE, FLASH_MIDDLE. Details se attached file. Hope this helps.
[HMIP_BSL.txt](https://github.com/hahn-th/homematicip-rest-api/files/15212974/HMIP_BSL.txt)
Regards
