### ISSUE TITLE
HmIP.Cloud HA Dump Config

### ISSUE THREAD

**Issue by milko-kookie** [hahn-th/homematicip-rest-api#524]
Hi, I have a handful of Prolicht Lights controlled by a HomematicIP Access Point and a Homematic DALI Gateway.
Would be great if they can be added to the library.

(apologies if this isn't formatted up to spec, the doc didn't mention anything about that)

[hmip-config_0F46.json](https://github.com/hahn-th/homematicip-rest-api/files/14972113/hmip-config_0F46.json)

Cheers,
M

**Comment by hahn-th** [comment]
One spec could be to add the device name to the title 😄

I added the device to this lib. But its readonly at the moment. There is another issue about the rgbw-dimmer #516. If i get the requested rest calls, this will work for the dali gateway too.
Do you use this lib in Home Assistant or just via cli?
