### ISSUE TITLE
Many entities and battery sensors are missing after updating home assistant 

### ISSUE THREAD

**Issue by HayderHekmat** [hahn-th/homematicip-rest-api#533]
Many entities and battery sensors are missing after updating home assistant to release 2024.7.

![image](https://github.com/hahn-th/homematicip-rest-api/assets/126294075/d3dbd7da-0630-481f-96b6-ef9c61100066)
![image](https://github.com/hahn-th/homematicip-rest-api/assets/126294075/c745f454-ded6-4503-bd4c-af70952c4a06)

**Comment by hahn-th** [comment]
Here is the issue: https://github.com/home-assistant/core/issues/121130
