### ISSUE TITLE
Missing devices

### ISSUE THREAD

**Issue by bbrinker** [hahn-th/homematicip-rest-api#540]
[hmip-config_5CA7.json](https://github.com/user-attachments/files/16887999/hmip-config_5CA7.json)

**Comment by hahn-th** [comment]
Should i assume what's missing?

**Comment by bbrinker** [comment]
Sorry, my mistake.

I missed the LED driver HMIP-RGBW.

 

Gruß

 

Burkhard Brinker

Rennerde 19

58769 Nachrodt-Wiblingwerde

Tel. :     +49 2352 31003

Mobil:   +49 173 5410159

E-Mail:  ***@***.*** ***@***.***> 

 

Von: hahn-th ***@***.***> 
Gesendet: Samstag, 7. Dezember 2024 09:01
An: hahn-th/homematicip-rest-api ***@***.***>
Cc: bbrinker ***@***.***>; Author ***@***.***>
Betreff: Re: [hahn-th/homematicip-rest-api] Missing devices (Issue #540)

 

Should i assume what's missing?
