### ISSUE TITLE
HCU1 SGTIN not recognized

### ISSUE THREAD

**Issue by tholenaar** [hahn-th/homematicip-rest-api#543]
Cannot add HCU1 as access point.

**Comment by hahn-th** [comment]
Could you please provide your config? 
and you have to betatest, because i am not able to do so.

**Comment by tholenaar** [comment]
Hi, thanks for reaching out. I am not a programmer but have been product owner of an SAP module in the past and am pretty familiar with testing. More than happy to assist. I have not used Homematic IP access point before but bought the HCU1 as it is potentially able to run locally instead of via the cloud. HCU1 is connected to a number of HMIP devices (mainly for floor heating) and I have a CCU3 connected via the CCU3 plug in. Discovered Home Assistant recently and am eagerly moving all my instances into this 1 front end. The HmIP-HCU1 SGTIN is 3014-F711-xxxxx. Just let me know what you need more and I'll do my best.

![Scherm­afbeelding 2024-10-30 om 15 17 27](https://github.com/user-attachments/assets/667a1d11-1642-41cf-9667-e9706b757b94)

**Comment by hahn-th** [comment]
I removed the id of your device from your comment

**Comment by iobrokerneu** [comment]
@hahn-th Hello, I also have an HCU1 and would like to help or test.
Best regards
Sascha

**Comment by iobrokerneu** [comment]
@hahn-th Can I send you the SGTIN privately so you can test it?

**Comment by hahn-th** [comment]
See #542 for more infos. @iobrokerneu maybe you could help.
