### ISSUE TITLE
HmIP-FALMOT-C12 is not showing up in my HA integartion

### ISSUE THREAD

**Issue by pagerhard** [hahn-th/homematicip-rest-api#544]
Hello, i hope you can help me, my HmIP-FALMOT-C12 inclduing the valve position is not listed in my Homeassistent integation, buit it is showing in the dump file correctly. I hope you can help me in this issue.
[dump.txt](https://github.com/user-attachments/files/17610476/dump.txt)

**Comment by umbertokek** [comment]
The FALMOT-C12 just got added recently into the dev branch of Home Assistant Core.
See [here](https://github.com/home-assistant/core/pull/122759)
To access it immeadiately switch to dev branch or wait for it to get into the stable branch (proably within November)
